### ISSUE TITLE
Dúvida sobre cleanup

### ISSUE THREAD

**Issue by rafaellcoellho** [AndreMicheletti/tdd_class#5]
No cleanup está desse jeito aqui. 

```python
keys = list(todos_list.keys())
    for t in keys:
        del todos_list[t]

size = range(len(logs))
    for i in size:
         del logs[i]
```

Mas no caso dos logs, ao ir removendo, dá index out of bounds. no caso de 3 logs:

primeira iteração [log 1, log 2, log 3], i = 0 -> deleta log 1
segunda iteração [log 2, log 3] , i = 1-> deleta log 3
terceira iterração [log 2] , i = 2 -> index out of bounds

Não seria melhor fazer um
```python
todos_list.clear()
logs.clear()
```

em ambos? ou to viajando? 

@AndreMicheletti

**Comment by AndreMicheletti** [comment]
Boa Rafael!

eu tinha feito assim pq eu tentei atribuir um valor para as variaveis e não funcionou, e tinha esquecido desse método `.clear()` kkkkkkk

funcionou melhor assim, ja dei push lá
Valeu!
